### ISSUE TITLE
音量调整

### ISSUE THREAD

**Issue by pionxzh** [hijiangtao/rainmood#3]
老哥能不能加个音量调整的
毕竟有时候还有其他人的语音讯息什么的
老把全局音量压下去不太方便

这个项目很赞 最近都听着呢

**Comment by hijiangtao** [comment]
@pionxzh 谢谢你的建议，已添加到 Todo 列表 #2 ，这周会加上。

**Comment by hijiangtao** [comment]
功能已加上，见 <https://github.com/hijiangtao/rainmood/releases/tag/v1.0.0-alpha>
